# parameters of the 2d homegeneous turbulence problem
nx : 2048         # NXF
ny : 2048         # NYF
re : 32.0e3      # Re, Reynolds number 
nt : 4000       # NT, number of time step
dt : 1.0e-3     # dt, time step
isolver : 1     # isolver; [1]arakawa [2] Central-difference [3] compact
icompact : 0    # [0] if non-compact [1] fourth-order, [2] sixth-order
ifm : 0         # [0] No closure [1] DSM [2] CNN
ipr : 4         # [1]TGV, [2]VM, [3]Shear, [4]Decay 
ip : 1          # ipoisson; [1]FST [2] MG5
its : 2         # its; [1]Euler [2] RK3
pfreq : 1       # print frequency
sfreq : 50       # save frequency
nsmovie : 100   # number of snapshots for movie
esplot : 4      # number of energy spectrum
kappa : 2       # DSM parameter
pCU3 : 0.0      # CU3 parameter
ichkp : 0       # start from checkpoint
nschkp : 2600   # snapshots to start from
mvchkp : 0      # movie checkpoint
