# parameters of the 2d homegeneous turbulence problem
nx : 1024         # NXF
ny : 1024         # NYF
nxc : 128         # NXC
nyc : 128         # NYC
re : 8.0e3      # Re, Reynolds number 
nt : 20000       # NT, number of time step
dt : 2.0e-4     # dt, time step
isolver : 1     # isolver; [1]arakawa [2] Central-difference [3] compact
icompact : 0    # [0] if non-compact [1] fourth-order, [2] sixth-order
ifm : 0         # [0] No closure [1] DSM [2] CNN
ipr : 4         # [1]TGV, [2]VM, [3]Shear, [4]Decay 
ip : 1          # ipoisson; [1]FST [2] MG5
its : 2         # its; [1]Euler [2] RK3
pfreq : 1       # print frequency
sfreq : 100       # save frequency
nsmovie : 100   # number of snapshots for movie
esplot : 4      # number of energy spectrum
kappa : 2       # DSM parameter
pCU3 : 0.0      # CU3 parameter
ichkp : 0       # start from checkpoint
nschkp : 0   # snapshots to start from
mvchkp : 0      # movie checkpoint
iapriori : 1    # [0] Do not save coarsen data, [1] Save coarsen data
imovie : 0      # [0] Do not save movie data, [1] Save movie data